name: CriLisCraft
main: com.criliscraft.plugin.CriLisCraft
author: Chaka
version: 2.0.4
commands:
   hat:
      description: Sets the players helmet to the item in their hand.
      usage: /<command>
