name: CriLisCraft
main: com.criliscraft.plugin.CriLisCraft
author: Chaka
version: 1.8-15.4.22-R1.0
commands:
   clc:
      description: The Main Command
      usage: /<command>
   hat:
      description: Hat command
      usage: /<command>
   kit:
      description: Experimenting with kits
      usage: /<command>
   die:
      description: An Amazing Death
      usage: /<command>